WITH exchange_rates AS (SELECT month, currency_code, coalesce(average_median_price, 1) as rate
                        FROM sys_currency_rate_mysql_t
                        WHERE currency_code = 'CNY'
                          AND del_flag = '0'
                          AND month >= '0000-00'
                          AND month <= '9999-99'
                          AND month like '____-__'
                        ORDER BY month DESC
                        LIMIT 1 BY month, currency_code),
    base_data AS (SELECT month,
    month_day,
    date,
    team_id,
    team_code,
    team_name,
    platform_id,
    platform_name,
    store_id,
    store_code,
    store_name,
    market_id,
    market_code,
    market_name,
    team_leader,
    sale_responsible,
    good_title,
    msku,
    asin,
    sku_name,
    sku_code,
    asin_url,
    sku_id,
    sku_type,
    sku_category_id,
    sku_category_name,
    three_category_id,
    three_category_name,
    brand_id,
    brand_name,
    shelf_time,
    opening_time,
    currency,
    sales_volume,
    fba_sales_volume,
    fbm_sales_volume,
    channel_sales_volume,
    liquidation_sales_volume,
    compensate_amount,
    refund_amount,
    fba_refund_amount,
    fbm_refund_amount,
    divide(sales_revenue, coalesce(er.rate, 1))                               AS sales_revenue,
    divide(fba_sales_revenue, coalesce(er.rate, 1))                           AS fba_sales_revenue,
    divide(fbm_sales_revenue, coalesce(er.rate, 1))                           AS fbm_sales_revenue,
    divide(other_income, coalesce(er.rate, 1))                                AS other_income,
    divide(promotional_discount, coalesce(er.rate, 1))                        AS promotional_discount,
    divide(buyer_ship_cost, coalesce(er.rate, 1))                             AS buyer_ship_cost,
    divide(gift_package_fee, coalesce(er.rate, 1))                            AS gift_package_fee,
    divide(clear_income, coalesce(er.rate, 1))                                AS clear_income,
    divide(return_sale_revenue, coalesce(er.rate, 1))                         AS return_sale_revenue,
    divide(refunds_other_income, coalesce(er.rate, 1))                        AS refunds_other_income,
    divide(refund_buyer_ship, coalesce(er.rate, 1))                           AS refund_buyer_ship,
    divide(refund_gift_package_fee, coalesce(er.rate, 1))                     AS refund_gift_package_fee,
    divide(refunds_promotional_discounts, coalesce(er.rate, 1))               AS refunds_promotional_discounts,
    divide(refund_commission, coalesce(er.rate, 1))                           AS refund_commission,
    divide(refund_fba_delivery_fee, coalesce(er.rate, 1))                     AS refund_fba_delivery_fee,
    divide(refund_point, coalesce(er.rate, 1))                                AS refund_point,
    divide(refund_other_transaction_expenses, coalesce(er.rate, 1))           AS refund_other_transaction_expenses,
    divide(refund_other_expenses, coalesce(er.rate, 1))                       AS refund_other_expenses,
    divide(sale_commission, coalesce(er.rate, 1))                             AS sale_commission,
    divide(delivery_fee, coalesce(er.rate, 1))                                AS delivery_fee,
    divide(fba_delivery_fee, coalesce(er.rate, 1))                            AS fba_delivery_fee,
    divide(additional_orders_channel_fba_delivery_fees,
    coalesce(er.rate, 1))                                              AS additional_orders_channel_fba_delivery_fees,
    divide(cost_adjustment, coalesce(er.rate, 1))                             AS cost_adjustment,
    divide(storage_fee, coalesce(er.rate, 1))                                 AS storage_fee,
    divide(other_expenses, coalesce(er.rate, 1))                              AS other_expenses,
    divide(return_process_fee, coalesce(er.rate, 1))                          AS return_process_fee,
    divide(pre_process_fee, coalesce(er.rate, 1))                             AS pre_process_fee,
    divide(unplanned_service_fee, coalesce(er.rate, 1))                       AS unplanned_service_fee,
    divide(other_storage_fee, coalesce(er.rate, 1))                           AS other_storage_fee,
    divide(vine_order, coalesce(er.rate, 1))                                  AS vine_order,
    divide(integral, coalesce(er.rate, 1))                                    AS integral,
    divide(account_manager_fee, coalesce(er.rate, 1))                         AS account_manager_fee,
    divide(secondary_resale_fee, coalesce(er.rate, 1))                        AS secondary_resale_fee,
    divide(other_transaction_cost, coalesce(er.rate, 1))                      AS other_transaction_cost,
    divide(other_platform_expenses, coalesce(er.rate, 1))                     AS other_platform_expenses,
    divide(commodity_price_tax, coalesce(er.rate, 1))                         AS commodity_price_tax,
    divide(promotion_discount_tax, coalesce(er.rate, 1))                      AS promotion_discount_tax,
    divide(buyer_freight_tax, coalesce(er.rate, 1))                           AS buyer_freight_tax,
    divide(gift_package_tax, coalesce(er.rate, 1))                            AS gift_package_tax,
    divide(market_withhold_tax, coalesce(er.rate, 1))                         AS market_withhold_tax,
    divide(other_tax_amount, coalesce(er.rate, 1))                            AS other_tax_amount,
    divide(sales_tax_rebate, coalesce(er.rate, 1))                            AS sales_tax_rebate,
    divide(refund_tax_commodity_price_tax, coalesce(er.rate, 1))              AS refund_tax_commodity_price_tax,
    divide(refund_tax_promotion_discount_tax, coalesce(er.rate, 1))           AS refund_tax_promotion_discount_tax,
    divide(refund_tax_buyer_freight_tax, coalesce(er.rate, 1))                AS refund_tax_buyer_freight_tax,
    divide(refund_tax_gift_package_tax, coalesce(er.rate, 1))                 AS refund_tax_gift_package_tax,
    divide(refund_tax_market_withhold_tax, coalesce(er.rate, 1))              AS refund_tax_market_withhold_tax,
    divide(procurement_cost, coalesce(er.rate, 1))                            AS procurement_cost,
    divide(inventory_cost, coalesce(er.rate, 1))                              AS inventory_cost,
    divide(other_offline_expenses, coalesce(er.rate, 1))                      AS other_offline_expenses,
    divide(compensate, coalesce(er.rate, 1))                                  AS compensate,
    divide(compensation_income, coalesce(er.rate, 1))                         AS compensation_income,
    divide(compensate_adjustment, coalesce(er.rate, 1))                       AS compensate_adjustment,
    divide(advertising_expenses, coalesce(er.rate, 1))                        AS advertising_expenses,
    divide(monthly_storage_fee, coalesce(er.rate, 1))                         AS monthly_storage_fee,
    divide(long_term_storage_fee, coalesce(er.rate, 1))                       AS long_term_storage_fee,
    divide(report_monthly_storage_fee, coalesce(er.rate, 1))                  AS report_monthly_storage_fee,
    divide(report_long_term_storage_fee, coalesce(er.rate, 1))                AS report_long_term_storage_fee,
    divide(excess_storage_fee, coalesce(er.rate, 1))                          AS excess_storage_fee,
    divide(warehouse_consolidation_fee, coalesce(er.rate, 1))                 AS warehouse_consolidation_fee,
    divide(inventory_removal_disposal_fee, coalesce(er.rate, 1))              AS inventory_removal_disposal_fee,
    divide(amazon_logistics_carrier_fee, coalesce(er.rate, 1))                AS amazon_logistics_carrier_fee,
    divide(awd_wh_charges, coalesce(er.rate, 1))                              AS awd_wh_charges,
    divide(awd_storage_fee, coalesce(er.rate, 1))                             AS awd_storage_fee,
    divide(awd_operating_cost, coalesce(er.rate, 1))                          AS awd_operating_cost,
    divide(awd_delivery_charge, coalesce(er.rate, 1))                         AS awd_delivery_charge,
    divide(deal, coalesce(er.rate, 1))                                        AS deal,
    divide(coupon, coalesce(er.rate, 1))                                      AS coupon,
    divide(subscription_fee, coalesce(er.rate, 1))                            AS subscription_fee,
    divide(atoz_complaint_fee, coalesce(er.rate, 1))                          AS atoz_complaint_fee,
    divide(liquidation_fee, coalesce(er.rate, 1))                             AS liquidation_fee,
    divide(other_unclassified_expenses, coalesce(er.rate, 1))                 AS other_unclassified_expenses,
    divide(clear_market_withhold_tax, coalesce(er.rate, 1))                   AS clear_market_withhold_tax,
    divide(clear_sale_revenue, coalesce(er.rate, 1))                          AS clear_sale_revenue,
    divide(value_added_tax, coalesce(er.rate, 1))                             AS value_added_tax,
    divide(order_cost, coalesce(er.rate, 1))                                  AS order_cost
FROM finance_platform_profit_item_t fppit final
    LEFT JOIN exchange_rates er ON er.month = fppit.month
WHERE del_flag = '0'
  and ((platform_id = 1 and store_id = 1788840085759098881 and market_id = 10))
  and month_day between '2025-12-17' and '2025-12-17'),
    aggregated_data AS (SELECT any(month)                                                 as month,
    any(date)                                                  as date,
    team_id,
    any(team_code)                                             as team_code,
    any(team_name)                                             as team_name,
    platform_id,
    any(platform_name)                                         as platform_name,
    store_id,
    any(store_code)                                            as store_code,
    any(store_name)                                            as store_name,
    market_id,
    any(market_code)                                           as market_code,
    any(market_name)                                           as market_name,
    any(team_leader)                                           as team_leader,
    any(currency)                                              as currency,
    sale_responsible,
    sum(sales_volume)                                          as sales_volume,
    sum(fba_sales_volume)                                      as fba_sales_volume,
    sum(fbm_sales_volume)                                      as fbm_sales_volume,
    sum(channel_sales_volume)                                  as channel_sales_volume,
    sum(liquidation_sales_volume)                              as liquidation_sales_volume,
    sum(compensate_amount)                                     as compensate_amount,
    sum(refund_amount)                                         as refund_amount,
    sum(fba_refund_amount)                                     as fba_refund_amount,
    sum(fbm_refund_amount)                                     as fbm_refund_amount,
    round(sum(sales_revenue), 2)                               as sales_revenue,
    round(sum(fba_sales_revenue), 2)                           as fba_sales_revenue,
    round(sum(fbm_sales_revenue), 2)                           as fbm_sales_revenue,
    round(sum(other_income), 2)                                as other_income,
    round(sum(promotional_discount), 2)                        as promotional_discount,
    round(sum(buyer_ship_cost), 2)                             as buyer_ship_cost,
    round(sum(gift_package_fee), 2)                            as gift_package_fee,
    round(sum(clear_income), 2)                                as clear_income,
    round(sum(return_sale_revenue), 2)                         as return_sale_revenue,
    round(sum(refunds_other_income), 2)                        as refunds_other_income,
    round(sum(refund_buyer_ship), 2)                           as refund_buyer_ship,
    round(sum(refund_gift_package_fee), 2)                     as refund_gift_package_fee,
    round(sum(refunds_promotional_discounts), 2)               as refunds_promotional_discounts,
    round(sum(refund_commission), 2)                           as refund_commission,
    round(sum(refund_fba_delivery_fee), 2)                     as refund_fba_delivery_fee,
    round(sum(refund_point), 2)                                as refund_point,
    round(sum(refund_other_transaction_expenses), 2)           as refund_other_transaction_expenses,
    round(sum(refund_other_expenses), 2)                       as refund_other_expenses,
    round(sum(sale_commission), 2)                             as sale_commission,
    round(sum(delivery_fee), 2)                                as delivery_fee,
    round(sum(fba_delivery_fee), 2)                            as fba_delivery_fee,
    round(sum(additional_orders_channel_fba_delivery_fees), 2) as additional_orders_channel_fba_delivery_fees,
    round(sum(cost_adjustment), 2)                             as cost_adjustment,
    round(sum(storage_fee), 2)                                 as storage_fee,
    round(sum(other_expenses), 2)                              as other_expenses,
    round(sum(return_process_fee), 2)                          as return_process_fee,
    round(sum(pre_process_fee), 2)                             as pre_process_fee,
    round(sum(unplanned_service_fee), 2)                       as unplanned_service_fee,
    round(sum(other_storage_fee), 2)                           as other_storage_fee,
    round(sum(vine_order), 2)                                  as vine_order,
    round(sum(integral), 2)                                    as integral,
    round(sum(account_manager_fee), 2)                         as account_manager_fee,
    round(sum(secondary_resale_fee), 2)                        as secondary_resale_fee,
    round(sum(other_transaction_cost), 2)                      as other_transaction_cost,
    round(sum(other_platform_expenses), 2)                     as other_platform_expenses,
    round(sum(commodity_price_tax), 2)                         as commodity_price_tax,
    round(sum(promotion_discount_tax), 2)                      as promotion_discount_tax,
    round(sum(buyer_freight_tax), 2)                           as buyer_freight_tax,
    round(sum(gift_package_tax), 2)                            as gift_package_tax,
    round(sum(market_withhold_tax), 2)                         as market_withhold_tax,
    round(sum(other_tax_amount), 2)                            as other_tax_amount,
    round(sum(sales_tax_rebate), 2)                            as sales_tax_rebate,
    round(sum(refund_tax_commodity_price_tax), 2)              as refund_tax_commodity_price_tax,
    round(sum(refund_tax_promotion_discount_tax), 2)           as refund_tax_promotion_discount_tax,
    round(sum(refund_tax_buyer_freight_tax), 2)                as refund_tax_buyer_freight_tax,
    round(sum(refund_tax_gift_package_tax), 2)                 as refund_tax_gift_package_tax,
    round(sum(refund_tax_market_withhold_tax), 2)              as refund_tax_market_withhold_tax,
    round(sum(procurement_cost), 2)                            as procurement_cost,
    round(sum(inventory_cost), 2)                              as inventory_cost,
    round(sum(other_offline_expenses), 2)                      as other_offline_expenses,
    round(sum(compensate), 2)                                  as compensate,
    round(sum(compensation_income), 2)                         as compensation_income,
    round(sum(compensate_adjustment), 2)                       as compensate_adjustment,
    round(sum(advertising_expenses), 2)                        as advertising_expenses,
    round(sum(monthly_storage_fee), 2)                         as monthly_storage_fee,
    round(sum(long_term_storage_fee), 2)                       as long_term_storage_fee,
    round(sum(report_monthly_storage_fee), 2)                  as report_monthly_storage_fee,
    round(sum(report_long_term_storage_fee), 2)                as report_long_term_storage_fee,
    round(sum(excess_storage_fee), 2)                          as excess_storage_fee,
    round(sum(warehouse_consolidation_fee), 2)                 as warehouse_consolidation_fee,
    round(sum(inventory_removal_disposal_fee), 2)              as inventory_removal_disposal_fee,
    round(sum(amazon_logistics_carrier_fee), 2)                as amazon_logistics_carrier_fee,
    round(sum(awd_wh_charges), 2)                              as awd_wh_charges,
    round(sum(awd_storage_fee), 2)                             as awd_storage_fee,
    round(sum(awd_operating_cost), 2)                          as awd_operating_cost,
    round(sum(awd_delivery_charge), 2)                         as awd_delivery_charge,
    round(sum(deal), 2)                                        as deal,
    round(sum(coupon), 2)                                      as coupon,
    round(sum(subscription_fee), 2)                            as subscription_fee,
    round(sum(atoz_complaint_fee), 2)                          as atoz_complaint_fee,
    round(sum(liquidation_fee), 2)                             as liquidation_fee,
    round(sum(other_unclassified_expenses), 2)                 as other_unclassified_expenses,
    round(sum(clear_market_withhold_tax), 2)                   as clear_market_withhold_tax,
    round(sum(clear_sale_revenue), 2)                          as clear_sale_revenue,
    round(sum(value_added_tax), 2)                             as value_added_tax,
    round(sum(order_cost), 2)                                  as order_cost
FROM base_data
GROUP BY team_id, platform_id, store_id, market_id, sale_responsible),
    calculated_metrics AS (SELECT *,
    refund_commission + refund_fba_delivery_fee + refund_point +
    refund_other_transaction_expenses + refund_other_expenses                      AS feeRefund,
    fba_delivery_fee + additional_orders_channel_fba_delivery_fees                 AS distributionFee,
    commodity_price_tax + promotion_discount_tax + buyer_freight_tax + gift_package_tax +
    market_withhold_tax +
    clear_market_withhold_tax                                                      AS salesTax,
    value_added_tax + other_tax_amount                                             AS valueAddedTaxTotal,
    refund_tax_commodity_price_tax + refund_tax_promotion_discount_tax +
    refund_tax_buyer_freight_tax + refund_tax_gift_package_tax +
    refund_tax_market_withhold_tax                                                 AS salesTaxRefund,
    integral + deal + coupon + vine_order                                          AS promotionFee,
    monthly_storage_fee + excess_storage_fee + long_term_storage_fee +
    warehouse_consolidation_fee + inventory_removal_disposal_fee + return_process_fee +
    amazon_logistics_carrier_fee + pre_process_fee + unplanned_service_fee +
    other_storage_fee + awd_storage_fee + awd_operating_cost +
    awd_delivery_charge                                                            AS storageFeeTotal,
    subscription_fee + account_manager_fee + atoz_complaint_fee + secondary_resale_fee +
    liquidation_fee + other_transaction_cost + other_platform_expenses + order_cost +
    other_unclassified_expenses                                                    AS otherFee,
    fba_sales_revenue + fbm_sales_revenue                                          AS salesVolumeAmount,
    clear_income + compensate + promotional_discount + buyer_ship_cost +
    gift_package_fee                                                               AS otherIncomeTotal,
    refund_buyer_ship + refund_gift_package_fee +
    refunds_promotional_discounts                                                  AS incomeRefund,
    procurement_cost + inventory_cost                                              AS totalCost,
    feeRefund + sale_commission + distributionFee + cost_adjustment + salesTax +
    valueAddedTaxTotal + salesTaxRefund + advertising_expenses + promotionFee +
    storageFeeTotal +
    otherFee                                                                       AS platformExpenditure,
    salesVolumeAmount + otherIncomeTotal + return_sale_revenue + incomeRefund      AS platformRevenue
FROM aggregated_data)
SELECT *,
       round(platformRevenue + platformExpenditure, 2)                                                      AS platformGrossProfit,
       round(platformRevenue + platformExpenditure + totalCost, 2)                                          AS salesGrossProfit,
       round(CASE
                 WHEN salesVolumeAmount = 0 THEN 0
                 WHEN (platformRevenue + platformExpenditure + totalCost) < 0 AND salesVolumeAmount < 0 THEN -(
                     (platformRevenue + platformExpenditure + totalCost) / salesVolumeAmount * 100)
                 ELSE (platformRevenue + platformExpenditure + totalCost) / salesVolumeAmount * 100 END,
             2)                                                                                             AS salesGrossProfitMargin,
       round(CASE
                 WHEN (platformExpenditure + totalCost) = 0 THEN 0
                 ELSE (platformRevenue + platformExpenditure + totalCost) / abs(platformExpenditure + totalCost) END,
             2)                                                                                             AS roi
FROM calculated_metrics
ORDER BY sales_revenue, team_id, platform_id, store_id, market_id, sale_responsible desc
LIMIT 0 , 2000;