<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.example</groupId>
    <artifactId>oceanlink</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>oceanlink-order</artifactId>
  <packaging>pom</packaging>
  <name>oceanlink-order</name>
  <description>订单域聚合父模块</description>

  <modules>
    <module>oceanlink-order-client</module>
    <module>oceanlink-order-domain</module>
    <module>oceanlink-order-app</module>
    <module>oceanlink-order-infrastructure</module>
    <module>oceanlink-order-adapter</module>
    <module>oceanlink-order-start</module>
  </modules>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
